### ISSUE TITLE
Backend configuration

### ISSUE THREAD

**Issue by josemic** [PDXostc/rvi_core#44]
See PDXostc/rvi_backend#37.

After digging in the Erlang code, I came to the conclusion, that the crash is caused by the dlink_bt being present at the backend side, however { proto_json_rpc, dlink_bt_rpc} not configured in 'backend.config'. Thus the service discovery registration message crashes the service discovery server, which therefore looses its ets-table and is re-initialized by the supervisior with an empty ets-table afterwards. 
This change in 'backend.config', even if BT is not used seems to solve it as workaround: 

```
	{ "", 
	  [
	   { proto_json_rpc, dlink_tcp_rpc},
	   { proto_json_rpc, dlink_bt_rpc}]
	}
```

**Comment by uwiger** [comment]
I will close this issue. Please create a new issue if it is still a problem.
