### ISSUE TITLE
Package URL 404'ing 

### ISSUE THREAD

**Issue by jeremiah** [PDXostc/rvi_core#57]
Hi,

Is this a working URL?: https://github.com/PDXostc/rvi_core/blob/release-0.4.0-debian_packaging/debian/rvi_0.4.0-1ubuntu1_amd64.deb

Jeremiah

**Comment by mfeuer** [comment]
Ubuntu package was removed from debian sub directory since it interfered with build.
Re-added as: https://github.com/PDXostc/rvi_core/blob/release-0.4.0-debian_packaging/rvi_0.4.0-1ubuntu1_amd64.deb?raw=true
